### PR TITLE
reworked bits of evaluation

### PR DESCRIPTION
**Pull request by Davidrxyang**
1. clarified what is "good" and "bad" and reworked network efficiency calculation

total network efficiency = (sum: complexity of each route * ridership of each route) * total cost

- higher complexity (greater distance, more transfers, more stops) is BAD
- higher complexity on a route with greater ridership is more BAD than higher complexity on a route with lower ridership. 
- greater cost is BAD
- following above definitions, greater total network efficiency value = WORSE EFFICIENCY
- a negative percent "improvement" is GOOD

2. implemented adjusted complexity

- complexity is adjusted higher if the geographical distance between origin and destination is smaller.

### CODE REVIEW

**Comment by Davidrxyang** [comment]
this one actually needs a lookover, sanity check my logic

**Comment by Davidrxyang** [comment]
#70

**Comment by henrydeng2002** [comment]
In adjustedRouteComplexity, you end up returning factor * simpleComplexity which ends up being simpleComplexity^2 / (adjustmentWeight * geographicalDistance). Not sure if the squaring is intentional
Otherwise I think logic looks good

**Comment by Davidrxyang** [comment]
Yea squaring is intentional

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by henrydeng2002** [comment]
looks good then

**Pull request merged**
