### PR TITLE
changed how efficiencies are updated and termination condition

### PR DESCRIPTION
**Pull request by henrydeng2002**
1. changed how efficiencies are updated: modified demand is now not recalculated (I think it is unnecessary to recalculate modified demand, since it is a measure of how "important" a connection is, and lines in lineCandidates shouldn't change the "importance" of a connection to the network, as lineCandidates lines aren't necessarily added to the network). Additionally, only the worst efficiency station pair is updated, and if the station pair is still the worst efficiency after the recalculation based on path, then choose it
2. fixed an issue with termination: previously if any line is shorter than minLength in targetEfficiencySatisfied(), the function returns false. Changed that to if any line is shorter than minLength, then the loop continues
3. added some additional logs

### CODE REVIEW

**Review by Davidrxyang — APPROVED** [review]
Lgtm, let's just make sure these changes are reflected in the paper. I will restart my 4 case runs on atlas when I land and have a stable network connection.

**Comment by Davidrxyang** [comment]
Is the new results file from a legitimate run?

**Comment by henrydeng2002** [comment]
> Is the new results file from a legitimate run?

idk I think its probably from one of my test runs, best to remove it and start again

**Comment by Davidrxyang** [comment]
> > Is the new results file from a legitimate run?
> 
> 
> 
> idk I think its probably from one of my test runs, best to remove it and start again

Ok. I created a Main.java inside algorithm that takes in a config file as a CLI argument. So run ./build and then java Algorithm.Main Algorithm/case1 , see the case1, case2 etc config files for the modified config file structure. The algo config file has a parameter that specifies the eval config file

**Pull request merged**
